server:
  port : 8081

powerjob:
  worker:
    protocol: akka
    # Whether to enable PowerJob Worker, default is true
    enabled: true
    # Akka port, default is 27777
    akka-port: 27777
    # Application name, used for grouping applications. Recommend to set the same value as project name.
    app-name: apollov2-iproject
    # Address of PowerJob-server node(s). Ip:port or domain. Multiple addresses should be separated with comma.
    server-address : localhost:7700
    # Store strategy of H2 database. disk or memory. Default value is disk.
    store-strategy : memory
    # Max length of result. Results that are longer than the value will be truncated.
    max-result-length: 8192
    # Max length of appended workflow context . Appended workflow context value that is longer than the value will be ignore.
    max-appended-wf-context-length: 8192
########### PowerJob-worker properties. ###########
# Whether to enable PowerJob Worker, default is true
#powerjob.worker.enabled=true
## Turn on test mode and do not force the server connection to be verified
#powerjob.worker.enable-test-mode=false
## Transport port, default is 27777
#powerjob.worker.port=27777
## Application name, used for grouping applications. Recommend to set the same value as project name.
#powerjob.worker.app-name=apollov2-iproject
## Address of PowerJob-server node(s). Ip:port or domain. Multiple addresses should be separated with comma.
#powerjob.worker.server-address=127.0.0.1:7700
## transport protocol between server and worker
#powerjob.worker.protocol=http
## Store strategy of H2 database. disk or memory. Default value is disk.
#powerjob.worker.store-strategy=memory
## Max length of result. Results that are longer than the value will be truncated.
#powerjob.worker.max-result-length=4096
## Max length of appended workflow context . Appended workflow context value that is longer than the value will be ignore.
#powerjob.worker.max-appended-wf-context-length=4096